### PR TITLE
Add new features

### PR DESCRIPTION
**Pull request by Ghostexvan**
* Features:
  - Add hand gesture controller in the Launcher Scene.
  - Add car selection.

* Error fixed:
  - Now we can FINALLY ENTER THE GAMEPLAY (used to be not cuz my laziness in developing the car selection feature).

image

### CODE REVIEW

**Review by yuurichan — APPROVED** [review]
GHlpBhcWMAAdL_m

**Comment by yuurichan** [comment]
my brother in Christ what the heck is a Hoshilo asset

**Comment by Ghostexvan** [comment]
I thought you said you have Hoshino riding whale model?

**Comment by Ghostexvan** [comment]
> my brother in Christ what the heck is a Hoshilo asset

I thought you said you have Hoshino riding whale model?

**Comment by yuurichan** [comment]
Oh that you meant.
Yeah I do have it, but I'm leaving it for last since there are things that needed to be taken care of.
(mostly the car physics ohhh i cant stand the car physics)
image

**Pull request merged**
